language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm i
  - bower i
  - gulp test
  - gulp release
  
deploy:
  provider: heroku
  api_key:
    secure: JNXQ8eX36u2Ec6zZcp5rSc03U4521y9Luir0HxxdA5RK8Q61UIu3NQCSPLbFSy5raC8FWepMvkpmBP4VN6aw5WphgODVRb0daUCJ5Z2oYp1L+H6aR5Flk32Pd4z1jPlsijh9s31hj456D9Y7JIKEzwGinuXro/CSWKfby1RsT+hoJ1Ixgac6yp5nl2EOE4p6ciLPNis2RiH0UkOwYAGueuZXwkCf0zZiNSjGPi9RsFfKD5GIsDQuMY9L6+zE4KdqX/yNGxcJU/8iUnPc4XpE0VrE6pQOsHoPsiZ8eWC/NcHjE3l9XhB79klzOUFa6BKLnRSWvdO6BswnaVrd5nZMC0RECJaqBT3Fa/Z3DSD60aAz67b92mJwT8BHy/3SRg8Q+NphQ96jzxUGIbgso30jv1Pghq6ufJgN5awphcgTrVRRYflv7aSbPC3E6WaYwtvNC/RVkY8qUzjC9ZmxUI+3ofEOUzgIgNVIZRI8PILD05Hnnew5DC97I5OYsRBYT5NgeJ9RsStL8Y6FIj8oeUNnjLH1Ner7qm+NbTNS7qbdatKj5O1SyykZPiM8mbKo0MQNy7Wt/2gomv7u4fr5D3HCs0JynvIj2kTEkEI6Yv+FhXeUfU6vwPe09Iij7fiJLVxBX/GIgEPobPIB5SQlVAvYURADwojTjklO0giEU+dT+Rs=
  app: travelet
  on:
    repo: Wildhoney/Travelet.uk
